### ISSUE TITLE
Test landing page

### ISSUE THREAD

**Issue by breslavsky** [open-tutorials/cypress#2]
Please find all bugs on https://www.epic1h.com/

# UI/UX

- [ ] All the links are valid and lead to correct pages
- [ ] All the fields have placeholders
- [ ] All the mandatory fields are validated
- [ ] All the mandatory fields have asterix sign
- [ ] All the error messages match with the field label
- [ ] Home link is on every single page
- [ ] Confirmation message is displayed for any kind of update and delete operation
- [ ] Scroll bar appears only if required

# Security

- [ ] HTTPs is used
- [ ] Important information like password displays in encrypted format
- [ ] If password is changed user can't login with old password
- [ ] Error messages don't display any important information
- [ ] Cookies don't store passwords

# Cross browser testing

- [ ] Chrome >= 60
- [ ] FireFox >= ?
- [ ] Safari >= ?
- [ ] Opera >= ?
- [ ] Yandex >= ?

# Cross device testing

- [ ] iPhone >= 6
  - [ ] Chrome
  - [ ] Safari

**Comment by Vladimir4932** [comment]
- [ ]  🐞 [Stabilization doesn't work in video (in the round)](https://www.awesomescreenshot.com/video/13869035?key=d03820d9fd15914564a42de61d499845)
- [ ]  🐞 All arrows are broken in Safari (can't record video in Safari)

**Comment by Vladimir4932** [comment]
https://user-images.githubusercontent.com/92365254/211757975-78b4efe3-d8ed-41b2-a0f1-6d878dfeabc0.mov

@breslavsky  check please

**Comment by comrade-che** [comment]
Неверное время в описании "Живой обратной связи"

Страница: Туториал: ломаем приложение онлайн-банка https://www.epic1h.com/became_a_tester

ОР: В 20.00 по Москве нажми на ссылку
ФР: В 18.00 по Москве нажми на ссылку

![1](https://user-images.githubusercontent.com/118734363/211779133-33fb060b-87e2-402f-a790-385ddf012140.png)
![2](https://user-images.githubusercontent.com/118734363/211779137-c210076d-c01b-4b27-9bf9-325e54fdbcf0.png)

**Comment by comrade-che** [comment]
Неверное описание действия в разделе "5. Смотрим логи на сервере"

Страница: Туториал: ломаем приложение онлайн-банка https://www.epic1h.com/became_a_tester

ОР: Кликните на ссылку,чтобы скачать файл. Откройте файл в редакторе. (Предположительно так)

![3](https://user-images.githubusercontent.com/118734363/211782828-c66aa215-0a49-462a-82ce-be6f89908d93.png)

ФР: Открой в новой вкладке https://ibank.epic1h.com/server.log. (При клике происходит скачивание файла)

**Comment by comrade-che** [comment]
Юзабилити улучшайзинг №2

![5](https://user-images.githubusercontent.com/118734363/211789300-a3e23305-37f0-4a72-b5b0-99bfe4fc7738.png)

**Comment by comrade-che** [comment]
Стрим-практикум: мемы учат/Что сделаем/Смотрим что у нас получится

![7](https://user-images.githubusercontent.com/118734363/211795698-42dcf382-d245-4eb7-9cc9-73cc66474e54.png)

**Comment by breslavsky** [comment]
> Стрим-практикум: мемы учат/Что сделаем/Смотрим что у нас получится
> 
> ![7](https://user-images.githubusercontent.com/118734363/211795698-42dcf382-d245-4eb7-9cc9-73cc66474e54.png)

Добавил прямую ссылку на проект.
