### ISSUE TITLE
Create thumbnail for stream

### ISSUE THREAD

**Issue by breslavsky** [open-tutorials/cypress#50]
> Привет, ребята!
> 
> Надеюсь вы уже пощупали мой последний туториал: собираем Conduit локально
> В нем мы используем Docker для установки базы данных Postgres.
> 
> И знаете, кого я вам приведу на стрим в четверг в 20:00 MSK?
> Мастера DevOps, Python гика, системного архитектора и моего замечательного друга Стаса.
> Стас управляет всей серверной инфраструктурой в нашей компании - это сотни тысяч запросов ежедневно.
> Он расскажет более подробно про Docker и покажет его возможности на реальных кейсах.
> 
> Полезность контента зашкаливает!
> 
> До встречи!

**Comment by breslavsky** [comment]
@slapshin please check

**Comment by NicroN37** [comment]
thumbnail variants 

![image](https://user-images.githubusercontent.com/117467298/218736891-54825a2f-7c3f-4b12-b4ee-6c68187529d1.png)

![image](https://user-images.githubusercontent.com/117467298/218752748-c397d4d5-1f37-4f5a-9fb9-db1e2c06620d.png)

**Comment by NicroN37** [comment]
edited

![image](https://user-images.githubusercontent.com/117467298/218988408-3a3dc19b-1058-4a1b-88d5-29308287ff27.png)
