### ISSUE TITLE
Spelling error in the text of Build conduit tutorial

### ISSUE THREAD

**Issue by Vivioza5** [open-tutorials/cypress#57]
# 🐞 Bugreport tutorial **Build conduit**

 * **Number:** 4
 * **Name:** Spelling error in the text
 * **Date:** 15/02/2023
 * **Project:** Open tutorials
 * **Part:** Text
 * **Severity:** Normal
 * **Priority:** Medium

 # Table of contents
 1. Behaviour
 2. Precondition
 3. Steps
 4. Actual result
 5. Expected result
 6. Possible causes
 7. Correction

 # 1. Behaviour
 * ** Device:** Any devices
 * **OS:** Any OS
 * **Screen:** any screens
 * **Browser:** Any browser
 * **Network parameters:** Any networks

# 2. Precondition
 1. Open [tutorial](https://www.epic1h.com/build_conduit) on computer

# 3. Steps
 
2. Scroll to point ["Минутка мотивации"](https://github.com/open-tutorials/cypress/blob/7aebe70895973aabd78e1374cc1dd45c9c7c82d8/tutorials/build_conduit.md?plain=1#L21)
3. Check [text](https://github.com/open-tutorials/cypress/blob/7aebe70895973aabd78e1374cc1dd45c9c7c82d8/tutorials/build_conduit.md?plain=1#L25) on the  page

# 4. Actual result
 Text is "Твой пусть тернист, но ты все сможешь, как это парень!"

 # 5. Expected result
 Text is "Твой путь тернист, но ты все сможешь, как этот парень!"

 # 6. Possible causes
 Mistake

 
 # 7. Correction
 Filled in by the developer in charge.
 
 * ** Responsible:**
 * **Date of correction:**
 * **Link to patch or commit:**
 * **Release link:**
 
 ## Factual causes

**Comment by breslavsky** [comment]
@Vladimir4932 please check

**Comment by Vladimir4932** [comment]
> 

Ok

**Comment by Vladimir4932** [comment]
The pull request was added.
