### ISSUE TITLE
Letter checking

### ISSUE THREAD

**Issue by Alex-QA-Test** [open-tutorials/cypress#71]
Как лучше реализовать данный текст кейс?

- Заходим на страницу регистрации
- Заполняем нужные поля, нажимаем кнопку "Далее"
-  Переходим на этап ввода пароля
У нас улетает запрос с заполненными данными и письмо с паролем. Идем например на MailHog, находим наше письмо, достаем из него пароль.
-  Возвращаемся на этап ввода пароля и вводим пароль.

**Comment by breslavsky** [comment]
Пожалуйста, перенесите вопрос в дискуссию.
