### ISSUE TITLE
Add screen casts for build conduit

### ISSUE THREAD

**Issue by breslavsky** [open-tutorials/cypress#79]
Firstly please provide steps where you want to add videos.

**Comment by Vladimir-Tarasov** [comment]
> Firstly please provide steps where you want to add videos.

1. Запуск проекта. 4 point. 
2. Инициализация базы данных. 6 point. 
3. Наполняем базу данных. 7 point. 
4. Сброс базы перед тестом. 8 point.

**Comment by breslavsky** [comment]
Я так подумал. Наверное нужно каждый шаг. Очень крутой туториал.
Ты можешь реза видео делать монтаж. Это очень легко, я покажу как на сдендапе.

**Comment by Vladimir-Tarasov** [comment]
Я предложил эти пункты по тому, что в других пунктах, как мне показалось,  ты очень подробно все объяснил в скринах и гифках. Но я думаю это не проблема записать все выполнение  и потом нарезать. Я раньше так уже делал

**Comment by breslavsky** [comment]
Да гуд.
